name: wildlife_strike_project
version: "1.0"
config-version: 2

profile: wildlife_strike_project

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  wildlife_strike_project:
    staging:
      +materialized: view
      +schema: "{{ var('stg_dataset', env_var('BQ_STG_DATASET', 'dev_stg')) }}"
    marts:
      +materialized: table
      +schema: "{{ var('mart_dataset', env_var('BQ_MART_DATASET', 'dev_mart')) }}"
